version: '2'
services: 
    man: 
        build:
            context: . 
            dockerfile: Dockerfile
        restart: always
        image: jupyterhub
        container_name: jupyterhub
        volumes: 
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        command: 
           jupyterhub --ip 0.0.0.0 --port 8000 
